export const Data = [
    {
        id: 1,
        name: 'The Born of APLEx',
        newPrice:26.00 ,
        type: 'Fantasy',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-cover-06-300x450.jpg',
    },
    {
        id: 2,
        name: 'The Throned Mirror',
        newPrice:23.00 ,
        type: 'Fantasy',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-cover-07-300x450.jpg',
    },
    {
        id: 3,
        name: 'Ark Forging',
        oldPrice: '$25.00',
        newPrice:20.00 ,
        type: 'Fantasy',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-cover-08-300x450.jpg',
    },
    {
        id: 4,
        name: 'The Sons of the Empire',
        oldPrice: '$26.00',
        newPrice:20.00 ,
        type: 'Fantasy',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-img-01-300x450.jpg',
    },
    {
        id: 5,
        name: 'Mists of Algorab',
        newPrice: 22.00 ,
        type: 'Fantasy',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-img-02-300x450.jpg',
    },
    {
        id: 6,
        name: 'Cyber Angel',
        newPrice: 20.00 ,
        type: 'Sci-Fi',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-img-05-300x450.jpg',
    },
    {
        id: 7,
        name: 'The Return of The King',
        oldPrice: '$32.00',
        newPrice:28.00 ,
        type: 'Fantasy',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-img-04-300x450.jpg',
    },
    {
        id: 8,
        name: '2024: Sanctuary',
        newPrice: 24.00 ,
        type: 'Sci-Fi',
        imgUrl: 'https://websitedemos.net/book-store-02/wp-content/uploads/sites/834/2021/05/author-book-store-book-img-03.jpg',
    },
]